export interface AtomItem {
  name: string
  value: string
  atom: string
  color?: string
  valueColor?: string
}

export type Nullable<T> = T | null | undefined

export const Atoms: Array<AtomItem> = [
  { name: '氢', atom: 'H', value: '1', color: '#6E9CB3', valueColor: '#8CBED9' },
  { name: '氦', atom: 'He', value: '2', color: '#D0C998', valueColor: '#D9D19E' },
  { name: '锂', atom: 'Li', value: '3', color: '#5B6C73', valueColor: '#A2A6AA' },
  { name: '铍', atom: 'Be', value: '4', color: '#B6AFB1', valueColor: '#CCCCCC' },
  { name: '硼', atom: 'B', value: '5', color: '#775454', valueColor: '#9E7878' },
  { name: '碳', atom: 'C', value: '6', color: '#3B3B3B', valueColor: '#878787' },
  { name: '氮', atom: 'N', value: '7', color: '#61C3B2', valueColor: '#7CD9C9' },
  { name: '氧', atom: 'O', value: '8', color: '#8FE89F', valueColor: '#AEFFBC' },
  { name: '氟', atom: 'F', value: '9', color: '#E6C47B', valueColor: '#FFDD9C' },
  { name: '氖', atom: 'Ne', value: '10', color: '#B03681', valueColor: '#8C2D6D' },
  { name: '钠', atom: 'Na', value: '11', color: '#D59A7C', valueColor: '#F2B695' },
  { name: '镁', atom: 'Mg', value: '12', color: '#967FDC', valueColor: '#A993F2' },
  { name: '铝', atom: 'Al', value: '13', color: '#838282', valueColor: '#C0C0C0' },
  { name: '硅', atom: 'Si', value: '14', color: '#48416D', valueColor: '#645D8C' },
  { name: '磷', atom: 'P', value: '15', color: '#C54F46', valueColor: '#E6685E' },
  { name: '硫', atom: 'S', value: '16', color: '#405B76', valueColor: '#6386A6' },
  { name: '氯', atom: 'Cl', value: '17', color: '#642677', valueColor: '#874B99' },
  { name: '氩', atom: 'Ar', value: '18', color: '#8F45A0', valueColor: '#A993F2' },
  { name: '钾', atom: 'K', value: '19', color: '#5B864D', valueColor: '#7DA66F' },
  { name: '钙', atom: 'Ca', value: '20', color: '#D9D9D8', valueColor: '#F2F2F2' },
  { name: '钪', atom: 'Sc', value: '21', color: '#75B67C', valueColor: '#9AD9A1' },
  { name: '钛', atom: 'Ti', value: '22', color: '#595958', valueColor: '#80807E' },
  { name: '钒', atom: 'V', value: '23', color: '#6C9DB7', valueColor: '#92C0D9' },
  { name: '铬', atom: 'Cr', value: '24', color: '#9F88B1', valueColor: '#BCA6CC' },
  { name: '锰', atom: 'Mn', value: '25', color: '#C9534E', valueColor: '#E67370' },
  { name: '铁', atom: 'Fe', value: '26', color: '#A6957F', valueColor: '#BFAF9B' },
  { name: '钴', atom: 'Co', value: '27', color: '#4B71DC', valueColor: '#6A8CEB' },
  { name: '镍', atom: 'Ni', value: '28', color: '#BBC299', valueColor: '#D4D9B4' },
  { name: '铜', atom: 'Cu', value: '29', color: '#AC5D41', valueColor: '#D9886D' },
  { name: '锌', atom: 'Zn', value: '30', color: '#B4B4B3', valueColor: '#D8D9D8' },
  { name: '镓', atom: 'Ga', value: '31', color: '#60B57B', valueColor: '#83D99F' },
  { name: '锗', atom: 'Ge', value: '32', color: '#969277', valueColor: '#BFBB9F' },
  { name: '砷', atom: 'As', value: '33', color: '#758496', valueColor: '#A1AFBF' },
  { name: '硒', atom: 'Se', value: '34' },
  { name: '溴', atom: 'Br', value: '35' },
  { name: '氪', atom: 'Kr', value: '36' },
  { name: '铷', atom: 'Rb', value: '37' },
  { name: '锶', atom: 'Sr', value: '38' },
  { name: '钇', atom: 'Y', value: '39' },
  { name: '锆', atom: 'Zr', value: '40' },
  { name: '铌', atom: 'Nb', value: '41' },
  { name: '钼', atom: 'Mo', value: '42' },
  { name: '锝', atom: 'Tc', value: '43' },
  { name: '钌', atom: 'Ru', value: '44' },
  { name: '铑', atom: 'Rh', value: '45' },
  { name: '钯', atom: 'Pd', value: '46' },
  { name: '银', atom: 'Ag', value: '47' },
  { name: '镉', atom: 'Cd', value: '48' },
  { name: '铟', atom: 'In', value: '49' },
  { name: '锡', atom: 'Sn', value: '50' },
  { name: '锑', atom: 'Sb', value: '51' },
  { name: '碲', atom: 'Te', value: '52' },
  { name: '碘', atom: 'I', value: '53' },
  { name: '氙', atom: 'Xe', value: '54' },
  { name: '铯', atom: 'Cs', value: '55' },
  { name: '钡', atom: 'Ba', value: '56' },
  { name: '镧', atom: 'La', value: '57' },
  { name: '铈', atom: 'Ce', value: '58' },
  { name: '镨', atom: 'Pr', value: '59' },
  { name: '钕', atom: 'Nd', value: '60' },
  { name: '钷', atom: 'Pm', value: '61' },
  { name: '钐', atom: 'Sm', value: '62' },
  { name: '铕', atom: 'Eu', value: '63' },
  { name: '钆', atom: 'Gd', value: '64' },
  { name: '铽', atom: 'Tb', value: '65' },
  { name: '镝', atom: 'Dy', value: '66' },
  { name: '钬', atom: 'Ho', value: '67' },
  { name: '铒', atom: 'Er', value: '68' },
  { name: '铥', atom: 'Tm', value: '69' },
  { name: '镱', atom: 'Yb', value: '70' },
  { name: '镥', atom: 'Lu', value: '71' },
  { name: '铪', atom: 'Hf', value: '72' },
  { name: '钽', atom: 'Ta', value: '73' },
  { name: '钨', atom: 'W', value: '74' },
  { name: '铼', atom: 'Re', value: '75' },
  { name: '锇', atom: 'Os', value: '76' },
  { name: '铱', atom: 'Ir', value: '77' },
  { name: '铂', atom: 'Pt', value: '78' },
  { name: '金', atom: 'Au', value: '79' },
  { name: '汞', atom: 'Hg', value: '80' },
  { name: '铊', atom: 'Tl', value: '81' },
  { name: '铅', atom: 'Pb', value: '82' },
  { name: '铋', atom: 'Bi', value: '83' },
  { name: '钋', atom: 'Po', value: '84' },
  { name: '砹', atom: 'At', value: '85' },
  { name: '氡', atom: 'Rn', value: '86' },
  { name: '钫', atom: 'Fr', value: '87' },
  { name: '镭', atom: 'Ra', value: '88' },
  { name: '锕', atom: 'Ac', value: '89' },
  { name: '钍', atom: 'Th', value: '90' },
  { name: '镤', atom: 'Pa', value: '91' },
  { name: '铀', atom: 'U', value: '92' },
  { name: '镎', atom: 'Np', value: '93' },
  { name: '钚', atom: 'Pu', value: '94' },
  { name: '镅', atom: 'Am', value: '95' },
  { name: '锔', atom: 'Cm', value: '96' },
  { name: '锫', atom: 'Bk', value: '97' },
  { name: '锎', atom: 'Cf', value: '98' },
  { name: '锿', atom: 'Es', value: '99' },
  { name: '镄', atom: 'Fm', value: '100' },
  { name: '钔', atom: 'Md', value: '101' },
  { name: '锘', atom: 'No', value: '102' },
  { name: '铹', atom: 'Lr', value: '103' },
  { name: '𬬻', atom: 'Rf', value: '104' },
  { name: '𬭊', atom: 'Db', value: '105' },
  { name: '𬭳', atom: 'Sg', value: '106' },
  { name: '𬭛', atom: 'Bh', value: '107' },
  { name: '𬭶', atom: 'Hs', value: '108' },
  { name: '鿏', atom: 'Mt', value: '109' },
  { name: '𫟼', atom: 'Ds', value: '110' },
  { name: '𬬭', atom: 'Rg', value: '111' },
  { name: '鿔', atom: 'Cn', value: '112' },
  { name: '鉨', atom: 'Nh', value: '113' },
  { name: '鈇', atom: 'Fl', value: '114' },
  { name: '镆', atom: 'Mc', value: '115' },
  { name: '鉝', atom: 'Lv', value: '116' }
  //   { name: 'tian', atom: 'Ts', value: '117' },
  //   { name: '奥', atom: 'Og', value: '118' }
]

export const AddAtom: AtomItem = { name: '+', atom: '+', value: '998', color: '#C94E42' }
export const SubAtom: AtomItem = { name: '-', atom: '-', value: '999', color: '#4E79BE' }
